// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFEc7gHDhMPqnCY25o_XWNWdnXCBqrmQ',
    appId: '1:973055720445:web:0696f6f4a8c457dbbcf794',
    messagingSenderId: '973055720445',
    projectId: 'my-task-manager-fe489',
    authDomain: 'my-task-manager-fe489.firebaseapp.com',
    storageBucket: 'my-task-manager-fe489.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-aE-t-fmwkgiLNDjbulApGGAtE7-ISU',
    appId: '1:973055720445:android:9fa2f8c3e0e6338abcf794',
    messagingSenderId: '973055720445',
    projectId: 'my-task-manager-fe489',
    storageBucket: 'my-task-manager-fe489.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zYQwymRPj98ZU7_xnx4a79HklMunWx4',
    appId: '1:973055720445:ios:1cdc133b5375cfc8bcf794',
    messagingSenderId: '973055720445',
    projectId: 'my-task-manager-fe489',
    storageBucket: 'my-task-manager-fe489.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zYQwymRPj98ZU7_xnx4a79HklMunWx4',
    appId: '1:973055720445:ios:1cdc133b5375cfc8bcf794',
    messagingSenderId: '973055720445',
    projectId: 'my-task-manager-fe489',
    storageBucket: 'my-task-manager-fe489.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAFEc7gHDhMPqnCY25o_XWNWdnXCBqrmQ',
    appId: '1:973055720445:web:a224b625a8f2d9ebbcf794',
    messagingSenderId: '973055720445',
    projectId: 'my-task-manager-fe489',
    authDomain: 'my-task-manager-fe489.firebaseapp.com',
    storageBucket: 'my-task-manager-fe489.firebasestorage.app',
  );
}
